DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;


CREATE TABLE urls (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   -- rem this line only for Hexlet checks
   -- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   created_at TIMESTAMP NOT NULL,
   CONSTRAINT pk_url PRIMARY KEY (id)
);

CREATE TABLE url_checks (
   id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   status_code INTEGER NOT NULL,
   title VARCHAR(100),
   h1 VARCHAR(100),
   description TEXT,
   url_id BIGINT NOT NULL,
   -- rem this line only for Hexlet checks
   -- created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   created_at TIMESTAMP NOT NULL,
   -- FOREIGN KEY (url_id) REFERENCES urls(id) ON DELETE CASCADE -- foreign key with cascade delete
   CONSTRAINT pk_url_checks PRIMARY KEY (id)
);